### ISSUE TITLE
Gatsby build fails

### ISSUE THREAD

**Issue by flogy** [flogy/gatsby-mdx-tts-example#1]
**Some facts:**
- `gatsby develop` is working fine, also when adding `SpeechOutput` components.
- `gatsby build` works as long as the `SpeechOutput` components are removed from `/content/posts/curses-and-counter-courses/index.mdx`
- `gatsby build` fails if `SpeechOutput` components are used

**Error message:**
The error message seems to point to an unhandled promise rejection. However, when handling it in the `gatsby-mdx-tts` plugin code there will be other errors. What stays the same is this:

`Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.htmlinvariant=31&args[]=%5Bobject%20Promise%5D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

**Speculation:**
I had problems before because there is some code only intended to be executed at build time (to generate the TTS files). For some reason it gets imported to the runtime / SSR when the `SpeechOutput` component is used.

To solve that original problem I have added the `browser` field to the plugin's `package.json` which has helped from including the TTS-generating code at runtime but it seems to now not be working for SSR...

```json
// Inside plugin's package.json
"main": "index.js",
"browser": "SpeechOutput.js",
```

**Comment by flogy** [comment]
Here is the full error log when running `gatsby build --no-uglify`:

```
info bootstrap finished - 10.933 s
⠀
success Building production JavaScript and CSS bundles - 9.633s
success Rewriting compilation hashes - 0.006s
success run queries - 10.258s - 10/10 0.97/s
[============================]   15.324 s 7/7 100% Generating image thumbnails
[                            ]   0.001 s 0/8 0% Building static HTML for pages
(node:21168) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at isStartNode (C:\Users\flogy\Documents\Development\gatsby-mdx-tts-example\public\render-page.js:59654:208)
    at one (C:\Users\flogy\Documents\Development\gatsby-mdx-tts-example\public\render-page.js:90314:18)
    at visitParents (C:\Users\flogy\Documents\Development\gatsby-mdx-tts-example\public\render-page.js:90307:3)
    at Object.visit [as default] (C:\Users\flogy\Documents\Development\gatsby-mdx-tts-example\public\render-page.js:90163:3)
    at Object.extractSpeechOutputBlocks [as default] (C:\Users\flogy\Documents\Development\gatsby-mdx-tts-example\public\render-page.js:59654:721)
    at C:\Users\flogy\Documents\Development\gatsby-mdx-tts-example\public\render-page.js:59640:3611
    at step (C:\Users\flogy\Documents\Development\gatsby-mdx-tts-example\public\render-page.js:59639:1898)
    at Object.next (C:\Users\flogy\Documents\Development\gatsby-mdx-tts-example\public\render-page.js:59639:1151)
    at C:\Users\flogy\Documents\Development\gatsby-mdx-tts-example\public\render-page.js:59639:809
    at new Promise (<anonymous>)
    at ./node_modules/gatsby-mdx-tts/index.js.__awaiter (C:\Users\flogy\Documents\Development\gatsby-mdx-tts-example\public\render-page.js:59639:442)
    at ./node_modules/gatsby-mdx-tts/index.js.module.exports (C:\Users\flogy\Documents\Development\gatsby-mdx-tts-example\public\render-page.js:59640:34
31)
    at d (C:\Users\flogy\Documents\Development\gatsby-mdx-tts-example\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:498)
    at Za (C:\Users\flogy\Documents\Development\gatsby-mdx-tts-example\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:39:16)
    at a.b.render (C:\Users\flogy\Documents\Development\gatsby-mdx-tts-example\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:44:476
)
    at a.b.read (C:\Users\flogy\Documents\Development\gatsby-mdx-tts-example\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:44:18)
(node:21168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without
 a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
failed Building static HTML for pages - 4.365s

 ERROR #95313 

Building static HTML failed for path "/curses-counter-curses-and-more"

See our docs page for more info on this error: https://gatsby.dev/debug-html



  Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Promise%5D&args[]= for the full mes
  sage or use the non-minified dev environment for full errors and additional helpful warnings.

  - react.production.min.js:19 S
    [gatsby-mdx-tts-example]/[react]/cjs/react.production.min.js:19:94

  - react.production.min.js:19 U
    [gatsby-mdx-tts-example]/[react]/cjs/react.production.min.js:19:229

  - react.production.min.js:20 V
    [gatsby-mdx-tts-example]/[react]/cjs/react.production.min.js:20:322

  - react.production.min.js:21 toArray
    [gatsby-mdx-tts-example]/[react]/cjs/react.production.min.js:21:261

  - react-dom-server.node.production.min.js:45 a.b.render
    [gatsby-mdx-tts-example]/[react-dom]/cjs/react-dom-server.node.production.min.js:45:176

  - react-dom-server.node.production.min.js:44 a.b.read
    [gatsby-mdx-tts-example]/[react-dom]/cjs/react-dom-server.node.production.min.js:44:18

  - react-dom-server.node.production.min.js:54 renderToString
    [gatsby-mdx-tts-example]/[react-dom]/cjs/react-dom-server.node.production.min.js:54:364

  - render-page.js:616 Module../.cache/static-entry.js.__webpack_exports__.default
    C:/Users/flogy/Documents/Development/gatsby-mdx-tts-example/public/render-page.js:616:28

  - render-html.js:35 Promise
    [gatsby-mdx-tts-example]/[gatsby]/dist/utils/worker/render-html.js:35:36

  - debuggability.js:384 Promise._execute
    [gatsby-mdx-tts-example]/[bluebird]/js/release/debuggability.js:384:9

  - promise.js:518 Promise._resolveFromExecutor
    [gatsby-mdx-tts-example]/[bluebird]/js/release/promise.js:518:18

  - promise.js:103 new Promise
    [gatsby-mdx-tts-example]/[bluebird]/js/release/promise.js:103:10

  - render-html.js:31 Promise.map.path
    [gatsby-mdx-tts-example]/[gatsby]/dist/utils/worker/render-html.js:31:37

  - util.js:16 tryCatcher
    [gatsby-mdx-tts-example]/[bluebird]/js/release/util.js:16:23

  - map.js:68 MappingPromiseArray._promiseFulfilled
    [gatsby-mdx-tts-example]/[bluebird]/js/release/map.js:68:38

  - promise_array.js:115 MappingPromiseArray.PromiseArray._iterate
    [gatsby-mdx-tts-example]/[bluebird]/js/release/promise_array.js:115:31


not finished Generating image thumbnails - 19.949s
```

**Comment by flogy** [comment]
Found a similar issue: https://github.com/gatsbyjs/gatsby/issues/7230

**Comment by flogy** [comment]
When adding some `console.log` output to the `index.ts` default export, it gets logged out after the bootstrap phase. This means it is actually called.

It might be that this is the case because some page queries are executed inside the [build phase](https://www.gatsbyjs.org/docs/overview-of-the-gatsby-build-process/#steps-of-the-build-phase), and thus the `gatsbyRemarkPlugin` are executed here again, e.g. to generate the HTML nodes of the MDX nodes?

Maybe it is worth to take a closer look on how [gatsby-remark-images](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-images) solves this...

**Comment by flogy** [comment]
Could resolve it by no longer using `axios` but the browser fetch API instead, removing the `browser` property in my `package.json` and importing the `<SpeechOutput>` component from `gatsby-mdx-tts/SpeechOutput`.
